openapi: 3.0.3
info:
  title: API - Loja de Roupas Física
  version: "1.0.0"
  description: >
    API responsável pelo gerenciamento de produtos, vendas, caixa e usuários da loja física.

servers:
  - url: http://localhost:3000
    description: Servidor local

paths:
  $ref: "./paths/index.yaml"

components:
  schemas:
    Produto:
      $ref: "./components/schemas/Produto.yaml#/Produto"
    Venda:
      $ref: "./components/schemas/Venda.yaml#/Venda"
    Caixa:
      $ref: "./components/schemas/Caixa.yaml#/Caixa"
    Usuario:
      $ref: "./components/schemas/Usuario.yaml#/Usuario"
