openapi: 3.1.1
info:
  title: API de exemplo do instagram
  description: Uma api de teste
  version: 0.0.1

tags:
  - Usuarios
  - Postagens
  - Comentarios
  - Curtidas

paths:
  /api/usuarios:
    $ref: './paths/Usuario/Collection.yaml'
  /api/usuarios/{id}:
    $ref: './paths/Usuario/Item.yaml'
    

  /api/postagens:
    get:
      description: Buscar todos os posts
    post:
  /api/postagens/{id}:
    get:
    patch:
    delete:

components:
  schemas:
    Usuario:
      $ref: './components/Usuario.yaml'
    Post:
      $ref: './components/Post.yaml'
    Comentario:
      $ref: './components/Comentario.yaml'
    Curtida:
      $ref: './components/Curtida.yaml'